name: Run generate.sh script and Manage PR

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: generate-script
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0

      - name: Install apib2swagger
        run: npm install -g apib2swagger

      - name: Setup PHP and install Saloon SDK Generator
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: 8.2
          tools: crescat-io/saloon-sdk-generator

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Run generate.sh script
        run: |
          chmod +x ./generate.sh
          ./generate.sh

      - name: Create or update PR
        id: pr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto/generate-script"
          commit-message: "Automated update from generate.sh script"
          title: "Automated update from generate.sh script"
          body: "This pull request was automatically created or updated by GitHub Actions."
          delete-branch: true
